# To create the image
## docker build -t <name_of_image> .
## docker build --no-cache --progress=plain -t <name_of_image> . --> Verbose
# To launch a container and delete it after
## docker run --rm -it --memory="4g" --entrypoint /bin/bash <name_of_image>
# If not enough memory is included PETSc will make an error when make all test


# docker build --no-cache --progress=plain -t img_petsc -f Dockerfile_petsc . && docker run --rm -it --entrypoint /bin/bash img_petsc
# docker run --rm -it --entrypoint /bin/bash img_petsc

FROM ubuntu:18.04


RUN apt-get update && \
    apt-get upgrade -y


# To avoid the issue when timezone is asked
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Zurich
RUN apt-get install -y tzdata


RUN apt-get install -y  \
                       make \
                       gcc gfortran wget curl pkg-config build-essential \
                       gfortran openmpi-bin libopenmpi-dev \
                       python3 python3-pip python3-dev git python3-tk \
                       valgrind

# To link 'python' to python3
RUN ln -s /usr/bin/python3 /usr/bin/python && \
    ln -s /usr/bin/pip3 /usr/bin/pip
RUN pip install --upgrade pip

RUN pip install requests matplotlib numpy scipy mpi4py

ENV LIB_DIR='/usr/lib/'
WORKDIR /root/
RUN mkdir -p /root/tmp/
WORKDIR /root/tmp/


# PETSc
RUN curl -L -O http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-3.12.1.tar.gz
RUN tar xzf petsc-3.12.1.tar.gz
WORKDIR /root/tmp/petsc-3.12.1/
RUN ./configure --with-scalar-type=complex \
--with-mpiexec="mpiexec --allow-run-as-root" --with-mpi=1 \
--COPTFLAGS='-O3' --FOPTFLAGS='-O3' --CXXOPTFLAGS='-O3' \
--with-debugging=0 --prefix=${LIB_DIR} --download-scalapack \
--download-mumps --download-openblas
RUN make PETSC_DIR=$PWD PETSC_ARCH=arch-linux-c-opt all
RUN make PETSC_DIR=$PWD PETSC_ARCH=arch-linux-c-opt install
RUN make PETSC_DIR=${LIB_DIR} PETSC_ARCH="" test
ENV PETSC_DIR=${LIB_DIR}

WORKDIR /root/tmp/

# SLEPc
RUN curl -L -O https://gitlab.com/slepc/slepc/-/archive/v3.12.1/slepc-v3.12.1.tar.gz
RUN tar xzf slepc-v3.12.1.tar.gz
WORKDIR /root/tmp/slepc-v3.12.1/
RUN ./configure --prefix=${LIB_DIR}
RUN make SLEPC_DIR=$PWD PETSC_DIR=${LIB_DIR}
